Repository SolonEDU/solon-mobile, pull requests merged in 2019-12, with the labels that each got.

#54 ui-ux-0
  CHANGELOG.md
  lib/auth/sign_in.dart
  lib/auth/welcome.dart
Labels: enhancement

#58 ui-ux-1
  CHANGELOG.md
  lib/auth/sign_in.dart
  lib/auth/sign_up.dart
  lib/auth/welcome.dart
  lib/home_screen.dart
Labels: enhancement

#60 forum
  CHANGELOG.md
  lib/api/api_connect.dart
  lib/forum/card.dart
  lib/forum/page.dart
  lib/forum/screen.dart
  lib/proposal/card.dart
Labels: enhancement, forum

#61 ui-ux-2
  CHANGELOG.md
  lib/api/api_connect.dart
  lib/auth/sign_in.dart
  lib/auth/sign_up.dart
  lib/auth/welcome.dart
  lib/forum/card.dart
  lib/forum/page.dart
  lib/forum/screen.dart
  lib/proposal/card.dart
  lib/proposal/page.dart
Labels: enhancement

#62 cleanup
  CHANGELOG.md
  lib/api/api_connect.dart
  lib/api/comment.dart
  lib/api/event.dart
  lib/api/forumpost.dart
  lib/api/login.dart
  lib/api/proposal.dart
  lib/api/register.dart
  lib/api/user.dart
  lib/api/vote.dart
  lib/auth/button.dart
  lib/auth/sign_in.dart
  lib/auth/sign_up.dart
  lib/auth/welcome.dart
  lib/forum/card.dart
  lib/forum/screen.dart
  lib/home_screen.dart
  lib/loader.dart
  lib/proposal/card.dart
  lib/proposal/screen.dart
Labels: help wanted

#52 db-api-0
  .flutter-plugins-dependencies
  .gitignore
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  ios/Flutter/flutter_export_environment.sh
  lib/account_screen.dart
  lib/admin/admin.dart
  lib/admin/event/create.dart
  lib/admin/event/page.dart
  lib/admin/event/screen.dart
  lib/admin/forum/card.dart
  lib/admin/forum/comment.dart
  lib/admin/forum/create.dart
  lib/admin/forum/page.dart
  lib/admin/forum/screen.dart
  lib/admin/home_screen.dart
  lib/admin/proposal/addproposal_screen.dart
  lib/admin/proposal/proposal.dart
  lib/admin/proposal/proposal_screen.dart
  lib/admin/proposal/proposals_screen.dart
  lib/api/api_connect.dart
  lib/api/comment.dart
  lib/api/event.dart
  lib/api/message.dart
  lib/api/user.dart
  lib/api/vote.dart
  lib/auth/button.dart
  lib/auth/sign_in.dart
  lib/auth/sign_up.dart
  lib/auth/welcome.dart
  lib/event/card.dart
  lib/event/create.dart
  lib/event/page.dart
  lib/event/screen.dart
  lib/forum/card.dart
  lib/forum/comment.dart
  lib/forum/create.dart
  lib/forum/page.dart
  lib/forum/screen.dart
  lib/home_screen.dart
  lib/loader.dart
  lib/main.dart
  lib/parent/event/card.dart
  lib/parent/event/screen.dart
  lib/parent/forum/card.dart
  lib/parent/forum/page.dart
  lib/parent/forum/screen.dart
  lib/parent/home_screen.dart
  lib/parent/proposal/card.dart
  lib/parent/proposal/page.dart
  lib/parent/proposal/screen.dart
  lib/proposal/card.dart
  lib/proposal/create.dart
  lib/proposal/page.dart
  lib/proposal/screen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, forum, help wanted, proposal
